### ISSUE TITLE
Error Box main_thread not found

### ISSUE THREAD

**Issue by trickster0** [sy1ntexx/rusty-dll#1]
I am having an issue where main_thread is fine and is executed but I am also getting the error below. Any idea why?
Am i doing something wrong or is it a rust bug?

![image](https://user-images.githubusercontent.com/20028117/135056452-b1bc37e2-5384-4c8c-89f3-8a6885ab0672.png)

**Comment by sy1ntexx** [comment]
@trickster0 The problem might be caused because of compiler mangling the name of the function, can you try putting `#[no_mangle]` attribute on main_thread to see if it solves the problem?

**Comment by trickster0** [comment]
yea that was it, i figured it out yesterday
