### ISSUE TITLE
32bit build results in DllMain defined more than once

### ISSUE THREAD

**Issue by Therdel** [sy1ntexx/rusty-dll#2]
Using the x86 build script, I get the error that `DllMain` is defined more than once - again in `dll_dllmain_stub` in msvcrt: ([Full error output](https://gist.github.com/Therdel/72659e6d633b98b1a059753351b9fff4))

>   = note: lib.def : warning LNK4022: cannot find unique match for symbol 'DllMain'
>           lib.def : warning LNK4002: _DllMain@12 defined in d:\a01\_work\11\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\dll_dllmain_stub.obj
>           lib.def : warning LNK4002: _DllMain@8 defined in C:\Users\_____\dev\rusty-dll\..\target\i686-pc-windows-msvc\debug\deps\rusty_dll.28khj9chbjt87t9j.rcgu.o
>           lib.def : error LNK2001: unresolved external symbol DllMain
>           C:\Users\_____\dev\rusty-dll\../target\i686-pc-windows-msvc\debug\deps\rusty_dll.dll.lib : fatal error LNK1120: 1 unresolved externals

Stackoverflow [hints](https://stackoverflow.com/a/343467/9783596) that the problem might (!) be that the linking order of msvcrt and our code results in the `DllMain` of msvcrt not being dropped, resulting in multiple definitions. But I have no idea atm how to control this.

rustc 1.58.1 (db9d1b20b 2022-01-20)
Microsoft Windows [Version 10.0.19043.1526]

**Comment by sy1ntexx** [comment]
Closed with #3, thanks for the pr
